"""init

Revision ID: 70899d69372d
Revises: 82330713a9e4
Create Date: 2025-01-23 18:51:36.931134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70899d69372d'
down_revision: Union[str, None] = '82330713a9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_works')
    # ### end Alembic commands ###
