"""init

Revision ID: 8945267347a5
Revises: 70899d69372d
Create Date: 2025-01-23 21:38:44.854936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8945267347a5'
down_revision: Union[str, None] = '70899d69372d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_works', sa.Column('max_user_per_hour', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_works', 'max_user_per_hour')
    # ### end Alembic commands ###
