"""init

Revision ID: 8c1e8a7576ea
Revises: ac4dd94f8d44
Create Date: 2025-01-26 16:52:43.344139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1e8a7576ea'
down_revision: Union[str, None] = 'ac4dd94f8d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'comment')
    # ### end Alembic commands ###
