"""add training table

Revision ID: a8372da4ecc3
Revises: be514a6b3e4d
Create Date: 2025-02-10 14:04:59.787774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8372da4ecc3'
down_revision: Union[str, None] = 'be514a6b3e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('program', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings')
    # ### end Alembic commands ###
