"""add training table

Revision ID: ae2167f61d20
Revises: c793fae3947f
Create Date: 2025-02-12 17:04:27.291230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae2167f61d20'
down_revision: Union[str, None] = 'c793fae3947f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_programs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('program', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('program_male', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('program_female', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_column('users', 'program_female')
    op.drop_column('users', 'program')
    op.drop_column('users', 'program_male')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('program_male', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('program', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('program_female', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_table('training_programs')
    # ### end Alembic commands ###
