"""add training table

Revision ID: b3602f5a345b
Revises: ae2167f61d20
Create Date: 2025-02-12 17:07:40.723162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3602f5a345b'
down_revision: Union[str, None] = 'ae2167f61d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_programs', sa.Column('individual', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('training_programs', sa.Column('male', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('training_programs', sa.Column('female', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('training_programs', 'program')
    op.drop_column('training_programs', 'program_female')
    op.drop_column('training_programs', 'program_male')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_programs', sa.Column('program_male', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('training_programs', sa.Column('program_female', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('training_programs', sa.Column('program', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('training_programs', 'female')
    op.drop_column('training_programs', 'male')
    op.drop_column('training_programs', 'individual')
    # ### end Alembic commands ###
