"""init

Revision ID: baad36a96e3c
Revises: e272e01e4dcf
Create Date: 2025-01-24 22:43:09.038850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baad36a96e3c'
down_revision: Union[str, None] = 'e272e01e4dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_works', sa.Column('free_days', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('schedule_works', sa.Column('auto_confirmation', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_works', 'auto_confirmation')
    op.drop_column('schedule_works', 'free_days')
    # ### end Alembic commands ###
