"""add training table

Revision ID: c793fae3947f
Revises: a8372da4ecc3
Create Date: 2025-02-12 16:00:21.116417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c793fae3947f'
down_revision: Union[str, None] = 'a8372da4ecc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings')
    op.add_column('users', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('users', sa.Column('program', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('program_male', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('program_female', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'program_female')
    op.drop_column('users', 'program_male')
    op.drop_column('users', 'program')
    op.drop_column('users', 'comment')
    op.create_table('trainings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('program', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.user_id'], name='trainings_trainer_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='trainings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trainings_pkey')
    )
    # ### end Alembic commands ###
