"""init

Revision ID: e272e01e4dcf
Revises: 8945267347a5
Create Date: 2025-01-24 15:08:33.837013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e272e01e4dcf'
down_revision: Union[str, None] = '8945267347a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('is_confirmation', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'is_confirmation')
    # ### end Alembic commands ###
